#!/bin/sh

# Yeah, semicolons.  weird.  It's a windows thing.  export
#CLASSPATH=".;jruby-complete-1.7.21.jar;foa.jar;snakeyaml-1.9.jar" java -Xmx500m -Xss1024k org.jruby.Main main.rb
CLASSPATH=".;jruby-complete-9.4.13.0.jar;foa.jar;snakeyaml-1.9.jar" java -Xmx500m -Xss1024k org.jruby.Main main.rb
